version: '3'
services:
  db:
    image: mongo:3.4
  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - 3000:3000
  frontend:
    image: nginx:1.13
    volumes:
      - ./frontend:/usr/share/nginx/html/
    ports:
      - 80:80