volumes:
  dados:

networks:
  banco:
  web:
  fila:

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: senha_segura
    volumes:
      - dados:/var/lib/postgresql/data
      - ./scripts:/scripts
    networks:
      - banco

  app:
    image: python:3.6
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh ./app.sh
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue
    environment:
      - REDIS_HOST=queue
      - REDIS_PORT=6379
      - REDIS_DB=0
      - POSTGRES_DB=email_sender
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha_segura
      - POSTGRES_HOST=db
  frontend:
    image: nginx:1.13
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web
    depends_on:
      - app

  queue:
    image: redis:3.2
    networks:
      - fila
  worker:
    build: worker
    volumes:
    #worker
    - ./worker:/worker
    command: worker.py
    working_dir: /worker
    networks:
     - fila
    depends_on:
      - queue
